### ISSUE TITLE
Create a "Transfer Funds" button

### ISSUE THREAD

**Issue by Mansoor8484** [Mansoor8484/smartcash-1#33]
Allow the user to transfer their funds to different expenses they would like to save for. (Vacation, item, car, etc)

**Comment by hparcells** [comment]
Hi so I didn't really realize this task would have been created and that it is different from the Transactions page task #19, so some of it's already done, like the core classes and such. But I guess like the issue title suggests, a button needs to be created somewhere.

So some of the code is already on my `feat/transactions` branch, so given this task I'll merge it into develop later tonight

The transfer class:
https://github.com/Mansoor8484/smartcash-1/blob/feat/transactions/src/main/java/rebelalliance/smartcash/ledger/Transfer.java

**Comment by hparcells** [comment]
merged!
