### ISSUE TITLE
begin to think about how we can implement mfa

### ISSUE THREAD

**Issue by Mansoor8484** [Mansoor8484/smartcash-1#57]
Possible steps:

 
1. Choose an MFA Method: Decide which MFA method you want to implement. Common methods include:

2. Time-based One-Time Password (TOTP)
    SMS-based verification
    Email-based verification
    Push notifications
    Integrate an MFA Library: Depending on the method you choose, you might need to integrate a library into your 
    JavaFX application. For example, if you're implementing TOTP, you can use libraries like Google Authenticator's java- 
    libpam or Apache Commons Codec for generating and validating TOTP codes.

3. User Interface: Design the user interface for MFA. You might need to create screens for users to enable MFA, enter 
    verification codes, and manage their MFA settings.

4. Backend Integration: Implement backend logic to handle MFA setup, verification, and management. This includes 
    storing MFA settings securely and verifying the codes provided by users.

5. Testing: Thoroughly test your MFA implementation to ensure it works correctly in various scenarios, such as when 
    users enable, disable, or reset MFA.

**Comment by hparcells** [comment]
Standard OTP would be the easiest to implement. No need for an email service or SMS service which could cost money. These email and SMS options would be fun to implement in the future if we have time, or for other features.

Continuing/starting this requires #18 and #38 to be completed, optionally the database connectivity finished as well.

**Comment by Mansoor8484** [comment]
perfect, would standard OTP authenticate via sms?

**Comment by hparcells** [comment]
Users would be provided a QR code or a string of characters they would input into an app like Authy or Google Authenticator. Then every 30 seconds there would be a new code that is generated.
